---
- name: Wait for cloud-init to complete
  command: cloud-init status --wait
  changed_when: false

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all packages
  apt:
    upgrade: safe
  register: upgrade_result

- name: Install essential packages
  apt:
    name:
      - curl
      - wget
      - vim
      - git
      - htop
      - net-tools
      - ufw
    state: present

- name: Configure firewall - Allow SSH
  ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Configure firewall - Allow HTTP
  ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Enable firewall
  ufw:
    state: enabled

- name: Disable password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
  notify: Restart sshd

- name: Set timezone to UTC
  timezone:
    name: UTC
