---
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Ensure nginx is started and enabled
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Create application directory
  file:
    path: "{{ app_root }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0755'

- name: Remove default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload nginx

- name: Deploy nginx configuration
  template:
    src: epicbook.conf.j2
    dest: /etc/nginx/sites-available/epicbook
    owner: root
    group: root
    mode: '0644'
  notify: Reload nginx

- name: Enable epicbook site
  file:
    src: /etc/nginx/sites-available/epicbook
    dest: /etc/nginx/sites-enabled/epicbook
    state: link
  notify: Reload nginx

- name: Test nginx configuration
  command: nginx -t
  changed_when: false
